version: '3'

services:

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: gozero
    ports:
      - "3306:3306"
    volumes:
    - ./rpc/transform/model:/docker-entrypoint-initdb.d

  redis-dev:
    image: redis:latest
    ports:
      - "6379:6379"

  etcd-dev:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"